### ISSUE TITLE
Support serde's Serialize and Deserialize

### ISSUE THREAD

**Issue by svenstaro** [kangalioo/pyo3-chrono#2]
Hey, chrono has support for serde built in but using this crate you lose that support. I think it'd be cool for this crate to support a feature flag for this purpose so that if you had a serialize `NaiveDateTime` before it can still be automatically derived.

**Comment by kangalio** [comment]
Good idea! The trait implementations are added in f15524dfb50b51bc25825057196cebef4ee8fd96. If there are no objections, I can push it to crates.io as version 0.2.1.

**Comment by svenstaro** [comment]
Working fine here!

Thanks, would appreciate a release. :)

**Comment by kangalio** [comment]
Great, thanks for testing! Version 0.2.1 is now published.
